name: Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: build and pack
        run: yarn build
        run: yarn pack --out /artifacts/artifact.tgz
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "/artifacts/artifact.tgz"
          name: eman
